const AnualBalances = [
  {
    id: 1,
    savings: [
      { type: 1, amount: 1000 },
      { type: 2, amount: 0 },
    ],
    year: 2021,
    result: 130000,
    positive: true,
    balances: [
      {
        id: 1,
        anualBalanceId: 1,
        month: 1,
        totalIncomesResult: 10000,
        totalSpendingsResult: 5000,
        result: 5000,
        positive: true,
        incomes: [],
        spendings: [],
      },
      {
        id: 2,
        anualBalanceId: 1,
        month: 2,
        totalIncomesResult: 25000,
        totalSpendingsResult: 10000,
        result: 15000,
        positive: true,
        incomes: [],
        spendings: [],
      },
      {
        id: 3,
        anualBalanceId: 1,
        month: 3,
        totalIncomesResult: 150000,
        totalSpendingsResult: 50000,
        result: 100000,
        positive: true,
        incomes: [],
        spendings: [],
      },
      {
        id: 4,
        anualBalanceId: 1,
        month: 4,
        totalIncomesResult: 20000,
        totalSpendingsResult: 24200,
        result: -4200,
        positive: false,
        incomes: [],
        spendings: [],
      },
      {
        id: 5,
        anualBalanceId: 1,
        month: 5,
        totalIncomesResult: 18500,
        totalSpendingsResult: 500,
        result: 18000,
        positive: true,
        incomes: [],
        spendings: [],
      },
      {
        id: 6,
        anualBalanceId: 1,
        month: 6,
        totalIncomesResult: 35000,
        totalSpendingsResult: 45000,
        result: -10000,
        positive: false,
        incomes: [],
        spendings: [],
      },
      {
        id: 7,
        anualBalanceId: 1,
        month: 7,
        totalIncomesResult: 35000,
        totalSpendingsResult: 45000,
        result: -10000,
        positive: true,
        incomes: [],
        spendings: [],
      },
      {
        id: 8,
        anualBalanceId: 1,
        month: 8,
        totalIncomesResult: 35000,
        totalSpendingsResult: 45000,
        result: -10000,
        positive: true,
        incomes: [],
        spendings: [],
      },
      {
        id: 9,
        anualBalanceId: 1,
        month: 9,
        totalIncomesResult: 35000,
        totalSpendingsResult: 45000,
        result: -10000,
        positive: true,
        incomes: [],
        spendings: [],
      },
      {
        id: 10,
        anualBalanceId: 1,
        month: 10,
        totalIncomesResult: 35000,
        totalSpendingsResult: 45000,
        result: -10000,
        positive: true,
        incomes: [],
        spendings: [],
      },
      {
        id: 11,
        anualBalanceId: 1,
        month: 11,
        totalIncomesResult: 35000,
        totalSpendingsResult: 45000,
        result: -10000,
        positive: true,
        incomes: [],
        spendings: [],
      },
      {
        id: 12,
        anualBalanceId: 1,
        month: 12,
        totalIncomesResult: 35000,
        totalSpendingsResult: 45000,
        result: -10000,
        positive: true,
        incomes: [],
        spendings: [],
      },
    ],
    vehicles: [],
  },
  {
    id: 13,
    savings: [
      { type: 1, amount: 0 },
      { type: 2, amount: 0 },
    ],
    year: 2020,
    result: -25000,
    positive: false,
    balances: [
      {
        id: 1,
        anualBalanceId: 2,
        month: 1,
        totalIncomesResult: 10000,
        totalSpendingsResult: 5000,
        result: 5000,
        positive: true,
        incomes: [],
        spendings: [],
      },
      {
        id: 14,
        anualBalanceId: 2,
        month: 2,
        totalIncomesResult: 25000,
        totalSpendingsResult: 10000,
        result: 15000,
        positive: true,
        incomes: [],
        spendings: [],
      },
    ],
    vehicles: [],
  },
  {
    id: 3,
    savings: [
      { type: 1, amount: 0 },
      { type: 2, amount: 0 },
    ],
    year: 2019,
    result: 0,
    positive: true,
    balances: [],
    vehicles: [],
  },
  {
    id: 4,
    savings: [
      { type: 1, amount: 0 },
      { type: 2, amount: 0 },
    ],
    year: 2018,
    result: 0,
    positive: true,
    balances: [],
    vehicles: [],
  },
  {
    id: 5,
    savings: [
      { type: 1, amount: 0 },
      { type: 2, amount: 0 },
    ],
    year: 2017,
    result: 0,
    positive: true,
    balances: [],
    vehicles: [],
  },
];

export default AnualBalances;
